// Dynamic variables ($guid, $timestamp, $random*, ...) generated by our own logic, no
// faker dependency. A {{$name}} placeholder resolves to a fresh value per occurrence.
// Isomorphic: no node imports.

export interface DynamicVariable {
  name: string;
  description: string;
  example: string;
}

const rnd = (maxExclusive: number): number => Math.floor(Math.random() * maxExclusive);
const between = (min: number, maxExclusive: number): number => min + rnd(maxExclusive - min);
const pick = <T>(pool: readonly T[]): T => pool[rnd(pool.length)];
const randomString = (alphabet: string, length: number): string =>
  Array.from({ length }, () => alphabet[rnd(alphabet.length)]).join("");
const capitalize = (s: string): string => (s ? s[0].toUpperCase() + s.slice(1) : s);
const times = <T>(n: number, fn: () => T): T[] => Array.from({ length: n }, fn);

function uuid(): string {
  const c = (globalThis as { crypto?: { randomUUID?: () => string } }).crypto;
  if (c?.randomUUID) return c.randomUUID();
  const hex = randomString("0123456789abcdef", 32).split("");
  hex[12] = "4";
  hex[16] = "89ab"[rnd(4)];
  const h = hex.join("");
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-${h.slice(12, 16)}-${h.slice(16, 20)}-${h.slice(20)}`;
}

/** Local date in the `Wed Oct 01 2026 22:40:00 GMT+0530` style. */
function jsDate(d: Date): string {
  return d.toString().replace(/\s*\(.*\)\s*$/, "");
}

const ALPHA_NUMERIC = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
const ALPHA_NUMERIC_UPPER = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
const UPPER = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";

const COLORS = ["red", "green", "blue", "yellow", "purple", "fuchsia", "grey", "white", "black", "orange", "cyan", "lime"];
const ABBREVIATIONS = ["SQL", "PCI", "JSON", "HTTP", "TCP", "SSL", "API", "XML", "HDD", "SSD", "RAM", "USB"];
const LOCALES = ["ny", "sr", "si", "en", "fr", "de", "es", "it", "pt", "ja", "zh", "ru"];
const USER_AGENTS = [
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36",
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15",
  "Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0",
  "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148",
];
const FIRST_NAMES = ["Ethan", "Chandler", "Megane", "Connie", "Sylvan", "Jonathon", "Pablo", "Ruthe", "Iva", "Talon", "Quinten", "Casey", "Alia", "Lottie", "Jarrell", "Gwen", "Jaden", "Donnell"];
const LAST_NAMES = ["Schaden", "Schneider", "Willms", "Runolfsdottir", "Fay", "Kunze", "Gutkowski", "Smitham", "Kovacek", "Kerluke", "Johns", "Grady", "Armando", "Trevor", "Gracie"];
const JOB_AREAS = ["Mobility", "Intranet", "Configuration", "Operations", "Marketing", "Optimization", "Accountability", "Functionality", "Identity"];
const JOB_DESCRIPTORS = ["Forward", "Corporate", "Senior", "International", "Lead", "Global", "Dynamic", "Regional", "Principal", "Chief"];
const JOB_TYPES = ["Supervisor", "Manager", "Coordinator", "Director", "Engineer", "Specialist", "Liaison", "Analyst", "Administrator", "Officer"];
const CITIES = ["Spinkahaven", "Korbinburgh", "Lefflerport", "New Audreanne", "Port Domenica", "Lake Gabe", "East Citlalli", "South Anibal"];
const COUNTRIES = ["Lao People's Democratic Republic", "Kazakhstan", "Austria", "Cape Verde", "Moldova", "Chad", "Norway", "Brazil", "Japan", "Kenya"];
const COUNTRY_CODES = ["CV", "MD", "TD", "US", "GB", "DE", "FR", "JP", "BR", "IN", "KE", "AU"];
const CURRENCY_CODES = ["CDF", "ZMK", "GNF", "USD", "EUR", "GBP", "JPY", "INR", "BRL", "AUD"];
const CURRENCY_NAMES = ["CFP Franc", "Cordoba Oro", "Pound Sterling", "US Dollar", "Euro", "Japanese Yen", "Indian Rupee", "Brazilian Real"];
const BS_ADJECTIVES = ["viral", "24/7", "24/365", "back-end", "next-generation", "value-added", "frictionless", "robust"];
const BS_BUZZ = ["repurpose", "harness", "transition", "leverage", "synergize", "incentivize", "morph", "engage"];
const BS_NOUNS = ["e-services", "markets", "interfaces", "schemas", "channels", "paradigms", "deliverables", "bandwidth"];
const CATCH_ADJECTIVES = ["Future-proofed", "Self-enabling", "Business-focused", "Down-sized", "Streamlined", "Synergistic", "Open-architected"];
const CATCH_DESCRIPTORS = ["heuristic", "bandwidth-monitored", "needs-based", "homogeneous", "client-server", "actuating", "executive"];
const CATCH_NOUNS = ["open architecture", "secured line", "superstructure", "installation", "infrastructure", "framework", "capability"];
const NOUNS = ["matrix", "bus", "bandwidth", "circuit", "transmitter", "protocol", "interface", "capacitor", "monitor", "firewall"];
const VERBS = ["parse", "quantify", "navigate", "synthesize", "calculate", "transmit", "program", "index", "override", "compress"];
const ING_VERBS = ["synthesizing", "navigating", "backing up", "parsing", "quantifying", "indexing", "transmitting", "compressing"];
const ADJECTIVES = ["auxiliary", "multi-byte", "back-end", "primary", "open-source", "virtual", "digital", "redundant", "solid state", "cross-platform"];
const WORD_POOL = ["withdrawal", "infrastructures", "circuit", "bandwidth", "matrix", "protocol", "synergy", "capacitor", "interface", "array"];
const LOREM_WORDS = [
  "lorem", "ipsum", "dolor", "sit", "amet", "consectetur", "adipiscing", "elit", "sed", "do", "eiusmod", "tempor",
  "incididunt", "labore", "magna", "aliqua", "enim", "minim", "veniam", "quis", "nostrud", "exercitation",
  "ullamco", "laboris", "aliquip", "commodo", "consequat", "duis", "aute", "irure", "voluptate", "velit",
];

const loremWords = (n: number): string => times(n, () => pick(LOREM_WORDS)).join(" ");
const loremSentence = (): string => capitalize(loremWords(between(4, 10))) + ".";
const loremParagraph = (): string => times(between(3, 7), loremSentence).join(" ");
const hex2 = (n: number): string => n.toString(16).padStart(2, "0");
const img = (topic?: string): string => `https://loremflickr.com/640/480${topic ? "/" + topic : ""}`;

const DEFINITIONS: [string, string, () => string][] = [
  // Common
  ["$guid", "A uuid-v4 style guid", uuid],
  ["$timestamp", "The current UNIX timestamp in seconds", () => String(Math.floor(Date.now() / 1000))],
  ["$isoTimestamp", "The current ISO timestamp at zero UTC", () => new Date().toISOString()],
  ["$randomUUID", "A random 36-character UUID", uuid],

  // Text, numbers, and colors
  ["$randomAlphaNumeric", "A random alpha-numeric character", () => ALPHA_NUMERIC[rnd(ALPHA_NUMERIC.length)]],
  ["$randomBoolean", "A random boolean value", () => String(rnd(2) === 0)],
  ["$randomInt", "A random integer between 0 and 1000", () => String(rnd(1001))],
  ["$randomColor", "A random color", () => pick(COLORS)],
  ["$randomHexColor", "A random hex value", () => "#" + rnd(0x1000000).toString(16).padStart(6, "0")],
  ["$randomAbbreviation", "A random abbreviation", () => pick(ABBREVIATIONS)],

  // Internet and IP addresses
  ["$randomIP", "A random IPv4 address", () => `${between(1, 256)}.${rnd(256)}.${rnd(256)}.${between(1, 256)}`],
  ["$randomIPV6", "A random IPv6 address", () => times(8, () => rnd(0x10000).toString(16).padStart(4, "0")).join(":")],
  ["$randomMACAddress", "A random MAC address", () => times(6, () => hex2(rnd(256))).join(":")],
  ["$randomPassword", "A random 15-character alpha-numeric password", () => randomString(ALPHA_NUMERIC, 15)],
  ["$randomLocale", "A random two-letter language code (ISO 639-1)", () => pick(LOCALES)],
  ["$randomUserAgent", "A random user agent", () => pick(USER_AGENTS)],
  ["$randomProtocol", "A random internet protocol", () => pick(["http", "https"])],
  ["$randomSemver", "A random semantic version number", () => `${rnd(10)}.${rnd(20)}.${rnd(20)}`],

  // Names
  ["$randomFirstName", "A random first name", () => pick(FIRST_NAMES)],
  ["$randomLastName", "A random last name", () => pick(LAST_NAMES)],
  ["$randomFullName", "A random first and last name", () => `${pick(FIRST_NAMES)} ${pick(LAST_NAMES)}`],
  ["$randomNamePrefix", "A random name prefix", () => pick(["Dr.", "Ms.", "Mr.", "Mrs.", "Miss", "Mx."])],
  ["$randomNameSuffix", "A random name suffix", () => pick(["I", "II", "III", "IV", "Jr.", "Sr.", "MD", "DDS", "PhD", "DVM"])],

  // Profession
  ["$randomJobArea", "A random job area", () => pick(JOB_AREAS)],
  ["$randomJobDescriptor", "A random job descriptor", () => pick(JOB_DESCRIPTORS)],
  ["$randomJobTitle", "A random job title", () => `${pick(JOB_DESCRIPTORS)} ${pick(JOB_AREAS)} ${pick(JOB_TYPES)}`],
  ["$randomJobType", "A random job type", () => pick(JOB_TYPES)],

  // Phone, address, and location
  ["$randomPhoneNumber", "A random ten-digit phone number", () => `${between(200, 999)}-${between(100, 999)}-${between(1000, 9999)}`],
  ["$randomPhoneNumberExt", "A random phone number with extension (12 digits)", () => `${between(10, 99)}-${between(100, 999)}-${between(100, 999)}-${between(1000, 9999)}`],
  ["$randomCity", "A random city name", () => pick(CITIES)],
  ["$randomStreetName", "A random street name", () => `${pick(LAST_NAMES)} ${pick(["Street", "Island", "Springs", "Orchard", "Avenue", "Lane"])}`],
  ["$randomStreetAddress", "A random street address", () => `${between(100, 99999)} ${pick(LAST_NAMES)} ${pick(["Streets", "Orchard", "Avenue", "Lane", "Way"])}`],
  ["$randomCountry", "A random country", () => pick(COUNTRIES)],
  ["$randomCountryCode", "A random two-letter country code (ISO 3166-1 alpha-2)", () => pick(COUNTRY_CODES)],
  ["$randomLatitude", "A random latitude coordinate", () => (Math.random() * 180 - 90).toFixed(4)],
  ["$randomLongitude", "A random longitude coordinate", () => (Math.random() * 360 - 180).toFixed(4)],

  // Images
  ["$randomAvatarImage", "A random avatar image", () => `https://avatars.githubusercontent.com/u/${rnd(100000)}`],
  ["$randomImageUrl", "A URL of a random image", () => img()],
  ["$randomAbstractImage", "A URL of a random abstract image", () => img("abstract")],
  ["$randomAnimalsImage", "A URL of a random animal image", () => img("animals")],
  ["$randomBusinessImage", "A URL of a random stock business image", () => img("business")],
  ["$randomCatsImage", "A URL of a random cat image", () => img("cats")],
  ["$randomCityImage", "A URL of a random city image", () => img("city")],
  ["$randomFoodImage", "A URL of a random food image", () => img("food")],
  ["$randomNightlifeImage", "A URL of a random nightlife image", () => img("nightlife")],
  ["$randomFashionImage", "A URL of a random fashion image", () => img("fashion")],
  ["$randomPeopleImage", "A URL of a random image of a person", () => img("people")],
  ["$randomNatureImage", "A URL of a random nature image", () => img("nature")],
  ["$randomSportsImage", "A URL of a random sports image", () => img("sports")],
  ["$randomTransportImage", "A URL of a random transportation image", () => img("transport")],
  ["$randomImageDataUri", "A random image data URI", () => "data:image/svg+xml;charset=UTF-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%2F%3E"],

  // Finance
  ["$randomBankAccount", "A random 8-digit bank account number", () => String(between(10000000, 99999999))],
  ["$randomBankAccountName", "A random bank account name", () => pick(["Home Loan Account", "Checking Account", "Savings Account", "Auto Loan Account", "Personal Loan Account", "Credit Card Account"])],
  ["$randomCreditCardMask", "A random masked credit card number", () => String(between(1000, 9999))],
  ["$randomBankAccountBic", "A random BIC (Bank Identifier Code)", () => randomString(UPPER, 4) + randomString(UPPER, 2) + randomString(ALPHA_NUMERIC_UPPER, 2)],
  ["$randomBankAccountIban", "A random 15-31 character IBAN", () => randomString(UPPER, 2) + between(10, 99) + randomString(ALPHA_NUMERIC_UPPER, between(11, 27))],
  ["$randomTransactionType", "A random transaction type", () => pick(["invoice", "payment", "deposit", "withdrawal"])],
  ["$randomCurrencyCode", "A random 3-letter currency code (ISO-4217)", () => pick(CURRENCY_CODES)],
  ["$randomCurrencyName", "A random currency name", () => pick(CURRENCY_NAMES)],
  ["$randomCurrencySymbol", "A random currency symbol", () => pick(["$", "£", "€", "¥", "₹", "₩"])],
  ["$randomBitcoin", "A random bitcoin address", () => pick(["1", "3", "bc1"]) + randomString(ALPHA_NUMERIC, between(25, 34))],

  // Business
  ["$randomCompanyName", "A random company name", () => `${pick(LAST_NAMES)} ${pick(["- " + pick(LAST_NAMES), "LLC", "Inc", "Group", "and Sons"])}`],
  ["$randomCompanySuffix", "A random company suffix", () => pick(["Inc", "LLC", "Group", "and Sons", "Ltd"])],
  ["$randomBs", "A random phrase of business-speak", () => `${pick(BS_ADJECTIVES)} ${pick(BS_BUZZ)} ${pick(BS_NOUNS)}`],
  ["$randomBsAdjective", "A random business-speak adjective", () => pick(BS_ADJECTIVES)],
  ["$randomBsBuzz", "A random business-speak buzzword", () => pick(BS_BUZZ)],
  ["$randomBsNoun", "A random business-speak noun", () => pick(BS_NOUNS)],

  // Catchphrases
  ["$randomCatchPhrase", "A random catchphrase", () => `${pick(CATCH_ADJECTIVES)} ${pick(CATCH_DESCRIPTORS)} ${pick(CATCH_NOUNS)}`],
  ["$randomCatchPhraseAdjective", "A random catchphrase adjective", () => pick(CATCH_ADJECTIVES)],
  ["$randomCatchPhraseDescriptor", "A random catchphrase descriptor", () => pick(CATCH_DESCRIPTORS)],
  ["$randomCatchPhraseNoun", "A random catchphrase noun", () => pick(CATCH_NOUNS)],

  // Databases
  ["$randomDatabaseColumn", "A random database column name", () => pick(["id", "title", "name", "email", "password", "group", "avatar", "status", "createdAt", "updatedAt", "token"])],
  ["$randomDatabaseType", "A random database type", () => pick(["tinyint", "smallint", "mediumint", "int", "bigint", "varchar", "text", "blob", "timestamp", "datetime", "decimal"])],
  ["$randomDatabaseCollation", "A random database collation", () => pick(["utf8_general_ci", "utf8_unicode_ci", "cp1250_bin", "cp1250_general_ci", "latin1_swedish_ci"])],
  ["$randomDatabaseEngine", "A random database engine", () => pick(["InnoDB", "MyISAM", "Memory", "CSV", "Archive", "Federated"])],

  // Dates
  ["$randomDateFuture", "A random future datetime", () => jsDate(new Date(Date.now() + between(1, 365) * 86400000))],
  ["$randomDatePast", "A random past datetime", () => jsDate(new Date(Date.now() - between(1, 365) * 86400000))],
  ["$randomDateRecent", "A random recent datetime", () => jsDate(new Date(Date.now() - between(1, 10080) * 60000))],
  ["$randomWeekday", "A random weekday", () => pick(["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"])],
  ["$randomMonth", "A random month", () => pick(["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"])],

  // Domains, emails, and usernames
  ["$randomDomainName", "A random domain name", () => `${pick(FIRST_NAMES).toLowerCase()}.${pick(["biz", "info", "name", "com", "net"])}`],
  ["$randomDomainSuffix", "A random domain suffix", () => pick(["com", "net", "org", "biz", "info", "name", "io"])],
  ["$randomDomainWord", "A random unqualified domain name", () => pick(FIRST_NAMES).toLowerCase()],
  ["$randomEmail", "A random email address", () => `${pick(FIRST_NAMES)}${rnd(100)}@${pick(["gmail.com", "hotmail.com", "yahoo.com"])}`],
  ["$randomExampleEmail", "A random email address from an example domain", () => `${pick(FIRST_NAMES)}${rnd(100)}@${pick(["example.com", "example.net", "example.org"])}`],
  ["$randomUserName", "A random username", () => `${pick(FIRST_NAMES)}${pick([".", "_", ""])}${pick(LAST_NAMES)}${rnd(100)}`],
  ["$randomUrl", "A random URL", () => `${pick(["https://", "http://"])}${pick(FIRST_NAMES).toLowerCase()}.${pick(["net", "com", "name", "info"])}`],

  // Files and directories
  ["$randomFileName", "A random file name", () => `${pick(LOREM_WORDS)}_${pick(LOREM_WORDS)}.${pick(["gdoc", "gif", "mp4v", "key", "sql", "txt"])}`],
  ["$randomFileType", "A random file type", () => pick(["application", "audio", "image", "message", "model", "multipart", "text", "video"])],
  ["$randomFileExt", "A random file extension", () => pick(["war", "book", "fsc", "gif", "key", "html", "mp3", "war", "wav"])],
  ["$randomCommonFileName", "A random common file name", () => `${pick(LOREM_WORDS)}.${pick(["mp4", "wav", "png", "jpg", "csv", "doc"])}`],
  ["$randomCommonFileType", "A random common file type", () => pick(["application", "audio", "image", "text", "video"])],
  ["$randomCommonFileExt", "A random common file extension", () => pick(["m2v", "wav", "png", "jpeg", "pdf", "doc", "csv"])],
  ["$randomFilePath", "A random file path", () => `/home/${pick(LOREM_WORDS)}_${pick(LOREM_WORDS)}.${pick(["cpio", "txt", "png", "log"])}`],
  ["$randomDirectoryPath", "A random directory path", () => pick(["/usr/bin", "/root", "/usr/local/bin", "/opt", "/var/log", "/home", "/etc"])],
  ["$randomMimeType", "A random MIME type", () => pick(["application/json", "text/plain", "image/png", "audio/mpeg", "video/mp4", "application/xml"])],

  // Stores
  ["$randomPrice", "A random price between 0.00 and 1000.00", () => (Math.random() * 1000).toFixed(2)],
  ["$randomProduct", "A random product", () => pick(["Towels", "Pizza", "Pants", "Cheese", "Chair", "Computer", "Shoes", "Gloves"])],
  ["$randomProductAdjective", "A random product adjective", () => pick(["Unbranded", "Incredible", "Tasty", "Handcrafted", "Refined", "Generic", "Rustic", "Ergonomic"])],
  ["$randomProductMaterial", "A random product material", () => pick(["Steel", "Plastic", "Frozen", "Concrete", "Cotton", "Granite", "Rubber", "Wooden"])],
  ["$randomProductName", "A random product name", () => `${pick(["Handmade", "Refined", "Ergonomic", "Rustic"])} ${pick(["Concrete", "Steel", "Rubber", "Cotton"])} ${pick(["Tuna", "Hat", "Chair", "Shoes"])}`],
  ["$randomDepartment", "A random commerce category", () => pick(["Tools", "Movies", "Electronics", "Books", "Garden", "Toys", "Health", "Music"])],

  // Grammar
  ["$randomNoun", "A random noun", () => pick(NOUNS)],
  ["$randomVerb", "A random verb", () => pick(VERBS)],
  ["$randomIngverb", "A random verb ending in -ing", () => pick(ING_VERBS)],
  ["$randomAdjective", "A random adjective", () => pick(ADJECTIVES)],
  ["$randomWord", "A random word", () => pick(WORD_POOL)],
  ["$randomWords", "Some random words", () => capitalize(times(between(2, 6), () => pick(WORD_POOL)).join(" "))],
  ["$randomPhrase", "A random phrase", () => `${pick(["You can't", "Try to", "We need to", "I'll"])} ${pick(VERBS)} the ${pick(NOUNS)}!`],

  // Lorem ipsum
  ["$randomLoremWord", "A random word of lorem ipsum text", () => pick(LOREM_WORDS)],
  ["$randomLoremWords", "Some random words of lorem ipsum text", () => loremWords(between(2, 5))],
  ["$randomLoremSentence", "A random sentence of lorem ipsum text", loremSentence],
  ["$randomLoremSentences", "A random 2 to 6 sentences of lorem ipsum text", () => times(between(2, 7), loremSentence).join(" ")],
  ["$randomLoremParagraph", "A random paragraph of lorem ipsum text", loremParagraph],
  ["$randomLoremParagraphs", "3 random paragraphs of lorem ipsum text", () => times(3, loremParagraph).join("\n")],
  ["$randomLoremText", "A random amount of lorem ipsum text", () => times(between(3, 8), loremSentence).join(" ")],
  ["$randomLoremSlug", "A random lorem ipsum URL slug", () => times(3, () => pick(LOREM_WORDS)).join("-")],
  ["$randomLoremLines", "1 to 5 random lines of lorem ipsum", () => times(between(1, 6), loremSentence).join("\n")],
];

const GENERATORS = new Map<string, () => string>(DEFINITIONS.map(([name, , gen]) => [name.toLowerCase(), gen]));

function example(gen: () => string): string {
  try {
    const s = gen();
    return s.length > 48 ? s.slice(0, 48) + "..." : s;
  } catch {
    return "";
  }
}

/** The full catalog in display order, for autocomplete and hover hints. */
export const DYNAMIC_VARIABLES: DynamicVariable[] = DEFINITIONS.map(([name, description, gen]) => ({
  name,
  description,
  example: example(gen),
}));

const CATALOG = new Map(DYNAMIC_VARIABLES.map((d) => [d.name.toLowerCase(), d]));

/** True if `name` (placeholder body, e.g. `$guid`) is a known dynamic variable. Case-insensitive. */
export function isDynamicVariable(name: string | undefined | null): boolean {
  return !!name && GENERATORS.has(name.trim().toLowerCase());
}

export function findDynamicVariable(name: string | undefined | null): DynamicVariable | undefined {
  return name ? CATALOG.get(name.trim().toLowerCase()) : undefined;
}

/** Generates a fresh value, or undefined if the name is not a dynamic variable. */
export function tryGenerate(name: string | undefined | null): string | undefined {
  if (!name) return undefined;
  const gen = GENERATORS.get(name.trim().toLowerCase());
  if (!gen) return undefined;
  try {
    return gen();
  } catch {
    return undefined;
  }
}
