using System.Globalization;
using System.Text;

namespace Yamlet.App.Services;

/// <summary>One dynamic variable's metadata, used to drive autocomplete and hover hints.</summary>
public sealed record DynamicVariable(string Name, string Description, string Example);

/// <summary>
/// Postman-style dynamic variables (<c>$guid</c>, <c>$timestamp</c>, <c>$random*</c>, …)
/// generated by our own logic — no external faker dependency. A <c>{{$name}}</c>
/// placeholder resolves to a freshly generated value each time it is used, so two
/// occurrences in the same request produce independent values (matching Postman).
/// <see cref="VariableResolver"/> falls back here when a placeholder is not a user
/// variable; the editor offers the <see cref="All"/> catalog for autocomplete.
/// </summary>
public static class DynamicVariables
{
    private static Random Rng => Random.Shared;

    /// <summary>The full catalog, in display order, for autocomplete and hints.</summary>
    public static IReadOnlyList<DynamicVariable> All { get; }

    private static readonly Dictionary<string, Func<string>> Generators;

    /// <summary>True if <paramref name="name"/> (placeholder body, e.g. <c>$guid</c>) is a known dynamic variable.</summary>
    public static bool IsDynamic(string? name) =>
        !string.IsNullOrEmpty(name) && Generators.ContainsKey(name.Trim());

    /// <summary>Generates a value for a dynamic variable, or returns false if the name is unknown.</summary>
    public static bool TryGenerate(string? name, out string value)
    {
        value = string.Empty;
        if (string.IsNullOrEmpty(name) || !Generators.TryGetValue(name.Trim(), out var gen))
        {
            return false;
        }

        try
        {
            value = gen();
            return true;
        }
        catch
        {
            value = string.Empty;
            return false;
        }
    }

    /// <summary>Looks up the catalog entry for a name, or null.</summary>
    public static DynamicVariable? Find(string? name) =>
        string.IsNullOrEmpty(name) ? null : _catalog.GetValueOrDefault(name.Trim());

    private static readonly Dictionary<string, DynamicVariable> _catalog;

    static DynamicVariables()
    {
        Generators = Definitions.ToDictionary(d => d.Name, d => d.Gen, StringComparer.OrdinalIgnoreCase);
        All = Definitions.Select(d => new DynamicVariable(d.Name, d.Description, Example(d.Gen))).ToList();
        _catalog = All.ToDictionary(d => d.Name, StringComparer.OrdinalIgnoreCase);
    }

    private static string Example(Func<string> gen)
    {
        try
        {
            var sample = gen();
            return sample.Length > 48 ? sample[..48] + "…" : sample;
        }
        catch
        {
            return string.Empty;
        }
    }

    // ---- Word pools ----------------------------------------------------------

    private const string AlphaNumeric = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
    private const string AlphaNumericUpper = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
    private const string Upper = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";

    private static readonly string[] Colors = { "red", "green", "blue", "yellow", "purple", "fuchsia", "grey", "white", "black", "orange", "cyan", "lime" };
    private static readonly string[] Abbreviations = { "SQL", "PCI", "JSON", "HTTP", "TCP", "SSL", "API", "XML", "HDD", "SSD", "RAM", "USB" };
    private static readonly string[] Locales = { "ny", "sr", "si", "en", "fr", "de", "es", "it", "pt", "ja", "zh", "ru" };

    private static readonly string[] UserAgents =
    {
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15",
        "Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0",
        "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148",
    };

    private static readonly string[] FirstNames = { "Ethan", "Chandler", "Megane", "Connie", "Sylvan", "Jonathon", "Pablo", "Ruthe", "Iva", "Talon", "Quinten", "Casey", "Alia", "Lottie", "Jarrell", "Gwen", "Jaden", "Donnell" };
    private static readonly string[] LastNames = { "Schaden", "Schneider", "Willms", "Runolfsdottir", "Fay", "Kunze", "Gutkowski", "Smitham", "Kovacek", "Kerluke", "Johns", "Grady", "Armando", "Trevor", "Gracie" };

    private static readonly string[] JobAreas = { "Mobility", "Intranet", "Configuration", "Operations", "Marketing", "Optimization", "Accountability", "Functionality", "Identity" };
    private static readonly string[] JobDescriptors = { "Forward", "Corporate", "Senior", "International", "Lead", "Global", "Dynamic", "Regional", "Principal", "Chief" };
    private static readonly string[] JobTypes = { "Supervisor", "Manager", "Coordinator", "Director", "Engineer", "Specialist", "Liaison", "Analyst", "Administrator", "Officer" };

    private static readonly string[] Cities = { "Spinkahaven", "Korbinburgh", "Lefflerport", "New Audreanne", "Port Domenica", "Lake Gabe", "East Citlalli", "South Anibal" };
    private static readonly string[] Countries = { "Lao People's Democratic Republic", "Kazakhstan", "Austria", "Cape Verde", "Moldova", "Chad", "Norway", "Brazil", "Japan", "Kenya" };
    private static readonly string[] CountryCodes = { "CV", "MD", "TD", "US", "GB", "DE", "FR", "JP", "BR", "IN", "KE", "AU" };

    private static readonly string[] CurrencyCodes = { "CDF", "ZMK", "GNF", "USD", "EUR", "GBP", "JPY", "INR", "BRL", "AUD" };
    private static readonly string[] CurrencyNames = { "CFP Franc", "Cordoba Oro", "Pound Sterling", "US Dollar", "Euro", "Japanese Yen", "Indian Rupee", "Brazilian Real" };

    private static readonly string[] BsAdjectives = { "viral", "24/7", "24/365", "back-end", "next-generation", "value-added", "frictionless", "robust" };
    private static readonly string[] BsBuzz = { "repurpose", "harness", "transition", "leverage", "synergize", "incentivize", "morph", "engage" };
    private static readonly string[] BsNouns = { "e-services", "markets", "interfaces", "schemas", "channels", "paradigms", "deliverables", "bandwidth" };

    private static readonly string[] CatchAdjectives = { "Future-proofed", "Self-enabling", "Business-focused", "Down-sized", "Streamlined", "Synergistic", "Open-architected" };
    private static readonly string[] CatchDescriptors = { "heuristic", "bandwidth-monitored", "needs-based", "homogeneous", "client-server", "actuating", "executive" };
    private static readonly string[] CatchNouns = { "open architecture", "secured line", "superstructure", "installation", "infrastructure", "framework", "capability" };

    private static readonly string[] Nouns = { "matrix", "bus", "bandwidth", "circuit", "transmitter", "protocol", "interface", "capacitor", "monitor", "firewall" };
    private static readonly string[] Verbs = { "parse", "quantify", "navigate", "synthesize", "calculate", "transmit", "program", "index", "override", "compress" };
    private static readonly string[] IngVerbs = { "synthesizing", "navigating", "backing up", "parsing", "quantifying", "indexing", "transmitting", "compressing" };
    private static readonly string[] Adjectives = { "auxiliary", "multi-byte", "back-end", "primary", "open-source", "virtual", "digital", "redundant", "solid state", "cross-platform" };
    private static readonly string[] WordPool = { "withdrawal", "infrastructures", "circuit", "bandwidth", "matrix", "protocol", "synergy", "capacitor", "interface", "array" };

    private static readonly string[] LoremWords =
    {
        "lorem", "ipsum", "dolor", "sit", "amet", "consectetur", "adipiscing", "elit", "sed", "do", "eiusmod", "tempor",
        "incididunt", "labore", "magna", "aliqua", "enim", "minim", "veniam", "quis", "nostrud", "exercitation",
        "ullamco", "laboris", "aliquip", "commodo", "consequat", "duis", "aute", "irure", "voluptate", "velit",
    };

    // ---- Generator catalog ---------------------------------------------------

    private static readonly (string Name, string Description, Func<string> Gen)[] Definitions =
    {
        // Common
        ("$guid", "A uuid-v4 style guid", () => Guid.NewGuid().ToString()),
        ("$timestamp", "The current UNIX timestamp in seconds", () => DateTimeOffset.UtcNow.ToUnixTimeSeconds().ToString(CultureInfo.InvariantCulture)),
        ("$isoTimestamp", "The current ISO timestamp at zero UTC", () => DateTime.UtcNow.ToString("yyyy-MM-ddTHH:mm:ss.fffZ", CultureInfo.InvariantCulture)),
        ("$randomUUID", "A random 36-character UUID", () => Guid.NewGuid().ToString()),

        // Text, numbers, and colors
        ("$randomAlphaNumeric", "A random alpha-numeric character", () => AlphaNumeric[Rng.Next(AlphaNumeric.Length)].ToString()),
        ("$randomBoolean", "A random boolean value", () => (Rng.Next(2) == 0).ToString().ToLowerInvariant()),
        ("$randomInt", "A random integer between 0 and 1000", () => Rng.Next(0, 1001).ToString(CultureInfo.InvariantCulture)),
        ("$randomColor", "A random color", () => Pick(Colors)),
        ("$randomHexColor", "A random hex value", () => $"#{Rng.Next(0x1000000):x6}"),
        ("$randomAbbreviation", "A random abbreviation", () => Pick(Abbreviations)),

        // Internet and IP addresses
        ("$randomIP", "A random IPv4 address", () => $"{Rng.Next(1, 256)}.{Rng.Next(256)}.{Rng.Next(256)}.{Rng.Next(1, 256)}"),
        ("$randomIPV6", "A random IPv6 address", RandomIPv6),
        ("$randomMACAddress", "A random MAC address", () => string.Join(":", Enumerable.Range(0, 6).Select(_ => Rng.Next(256).ToString("x2", CultureInfo.InvariantCulture)))),
        ("$randomPassword", "A random 15-character alpha-numeric password", () => RandomString(AlphaNumeric, 15)),
        ("$randomLocale", "A random two-letter language code (ISO 639-1)", () => Pick(Locales)),
        ("$randomUserAgent", "A random user agent", () => Pick(UserAgents)),
        ("$randomProtocol", "A random internet protocol", () => Pick(new[] { "http", "https" })),
        ("$randomSemver", "A random semantic version number", () => $"{Rng.Next(10)}.{Rng.Next(20)}.{Rng.Next(20)}"),

        // Names
        ("$randomFirstName", "A random first name", () => Pick(FirstNames)),
        ("$randomLastName", "A random last name", () => Pick(LastNames)),
        ("$randomFullName", "A random first and last name", () => $"{Pick(FirstNames)} {Pick(LastNames)}"),
        ("$randomNamePrefix", "A random name prefix", () => Pick(new[] { "Dr.", "Ms.", "Mr.", "Mrs.", "Miss", "Mx." })),
        ("$randomNameSuffix", "A random name suffix", () => Pick(new[] { "I", "II", "III", "IV", "Jr.", "Sr.", "MD", "DDS", "PhD", "DVM" })),

        // Profession
        ("$randomJobArea", "A random job area", () => Pick(JobAreas)),
        ("$randomJobDescriptor", "A random job descriptor", () => Pick(JobDescriptors)),
        ("$randomJobTitle", "A random job title", () => $"{Pick(JobDescriptors)} {Pick(JobAreas)} {Pick(JobTypes)}"),
        ("$randomJobType", "A random job type", () => Pick(JobTypes)),

        // Phone, address, and location
        ("$randomPhoneNumber", "A random ten-digit phone number", () => $"{Rng.Next(200, 999)}-{Rng.Next(100, 999)}-{Rng.Next(1000, 9999)}"),
        ("$randomPhoneNumberExt", "A random phone number with extension (12 digits)", () => $"{Rng.Next(10, 99)}-{Rng.Next(100, 999)}-{Rng.Next(100, 999)}-{Rng.Next(1000, 9999)}"),
        ("$randomCity", "A random city name", () => Pick(Cities)),
        ("$randomStreetName", "A random street name", () => $"{Pick(LastNames)} {Pick(new[] { "Street", "Island", "Springs", "Orchard", "Avenue", "Lane" })}"),
        ("$randomStreetAddress", "A random street address", () => $"{Rng.Next(100, 99999)} {Pick(LastNames)} {Pick(new[] { "Streets", "Orchard", "Avenue", "Lane", "Way" })}"),
        ("$randomCountry", "A random country", () => Pick(Countries)),
        ("$randomCountryCode", "A random two-letter country code (ISO 3166-1 alpha-2)", () => Pick(CountryCodes)),
        ("$randomLatitude", "A random latitude coordinate", () => (Rng.NextDouble() * 180 - 90).ToString("F4", CultureInfo.InvariantCulture)),
        ("$randomLongitude", "A random longitude coordinate", () => (Rng.NextDouble() * 360 - 180).ToString("F4", CultureInfo.InvariantCulture)),

        // Images
        ("$randomAvatarImage", "A random avatar image", () => $"https://avatars.githubusercontent.com/u/{Rng.Next(100000)}"),
        ("$randomImageUrl", "A URL of a random image", () => "https://loremflickr.com/640/480"),
        ("$randomAbstractImage", "A URL of a random abstract image", () => "https://loremflickr.com/640/480/abstract"),
        ("$randomAnimalsImage", "A URL of a random animal image", () => "https://loremflickr.com/640/480/animals"),
        ("$randomBusinessImage", "A URL of a random stock business image", () => "https://loremflickr.com/640/480/business"),
        ("$randomCatsImage", "A URL of a random cat image", () => "https://loremflickr.com/640/480/cats"),
        ("$randomCityImage", "A URL of a random city image", () => "https://loremflickr.com/640/480/city"),
        ("$randomFoodImage", "A URL of a random food image", () => "https://loremflickr.com/640/480/food"),
        ("$randomNightlifeImage", "A URL of a random nightlife image", () => "https://loremflickr.com/640/480/nightlife"),
        ("$randomFashionImage", "A URL of a random fashion image", () => "https://loremflickr.com/640/480/fashion"),
        ("$randomPeopleImage", "A URL of a random image of a person", () => "https://loremflickr.com/640/480/people"),
        ("$randomNatureImage", "A URL of a random nature image", () => "https://loremflickr.com/640/480/nature"),
        ("$randomSportsImage", "A URL of a random sports image", () => "https://loremflickr.com/640/480/sports"),
        ("$randomTransportImage", "A URL of a random transportation image", () => "https://loremflickr.com/640/480/transport"),
        ("$randomImageDataUri", "A random image data URI", () => "data:image/svg+xml;charset=UTF-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%2F%3E"),

        // Finance
        ("$randomBankAccount", "A random 8-digit bank account number", () => Rng.Next(10000000, 99999999).ToString(CultureInfo.InvariantCulture)),
        ("$randomBankAccountName", "A random bank account name", () => Pick(new[] { "Home Loan Account", "Checking Account", "Savings Account", "Auto Loan Account", "Personal Loan Account", "Credit Card Account" })),
        ("$randomCreditCardMask", "A random masked credit card number", () => Rng.Next(1000, 9999).ToString(CultureInfo.InvariantCulture)),
        ("$randomBankAccountBic", "A random BIC (Bank Identifier Code)", () => $"{RandomString(Upper, 4)}{RandomString(Upper, 2)}{RandomString(AlphaNumericUpper, 2)}"),
        ("$randomBankAccountIban", "A random 15-31 character IBAN", () => $"{RandomString(Upper, 2)}{Rng.Next(10, 99)}{RandomString(AlphaNumericUpper, Rng.Next(11, 27))}"),
        ("$randomTransactionType", "A random transaction type", () => Pick(new[] { "invoice", "payment", "deposit", "withdrawal" })),
        ("$randomCurrencyCode", "A random 3-letter currency code (ISO-4217)", () => Pick(CurrencyCodes)),
        ("$randomCurrencyName", "A random currency name", () => Pick(CurrencyNames)),
        ("$randomCurrencySymbol", "A random currency symbol", () => Pick(new[] { "$", "£", "€", "¥", "₹", "₩" })),
        ("$randomBitcoin", "A random bitcoin address", () => $"{Pick(new[] { "1", "3", "bc1" })}{RandomString(AlphaNumeric, Rng.Next(25, 34))}"),

        // Business
        ("$randomCompanyName", "A random company name", () => $"{Pick(LastNames)} {Pick(new[] { "- " + Pick(LastNames), "LLC", "Inc", "Group", "and Sons" })}"),
        ("$randomCompanySuffix", "A random company suffix", () => Pick(new[] { "Inc", "LLC", "Group", "and Sons", "Ltd" })),
        ("$randomBs", "A random phrase of business-speak", () => $"{Pick(BsAdjectives)} {Pick(BsBuzz)} {Pick(BsNouns)}"),
        ("$randomBsAdjective", "A random business-speak adjective", () => Pick(BsAdjectives)),
        ("$randomBsBuzz", "A random business-speak buzzword", () => Pick(BsBuzz)),
        ("$randomBsNoun", "A random business-speak noun", () => Pick(BsNouns)),

        // Catchphrases
        ("$randomCatchPhrase", "A random catchphrase", () => $"{Pick(CatchAdjectives)} {Pick(CatchDescriptors)} {Pick(CatchNouns)}"),
        ("$randomCatchPhraseAdjective", "A random catchphrase adjective", () => Pick(CatchAdjectives)),
        ("$randomCatchPhraseDescriptor", "A random catchphrase descriptor", () => Pick(CatchDescriptors)),
        ("$randomCatchPhraseNoun", "A random catchphrase noun", () => Pick(CatchNouns)),

        // Databases
        ("$randomDatabaseColumn", "A random database column name", () => Pick(new[] { "id", "title", "name", "email", "password", "group", "avatar", "status", "createdAt", "updatedAt", "token" })),
        ("$randomDatabaseType", "A random database type", () => Pick(new[] { "tinyint", "smallint", "mediumint", "int", "bigint", "varchar", "text", "blob", "timestamp", "datetime", "decimal" })),
        ("$randomDatabaseCollation", "A random database collation", () => Pick(new[] { "utf8_general_ci", "utf8_unicode_ci", "cp1250_bin", "cp1250_general_ci", "latin1_swedish_ci" })),
        ("$randomDatabaseEngine", "A random database engine", () => Pick(new[] { "InnoDB", "MyISAM", "Memory", "CSV", "Archive", "Federated" })),

        // Dates
        ("$randomDateFuture", "A random future datetime", () => DateTime.Now.AddDays(Rng.Next(1, 365)).ToString("ddd MMM dd yyyy HH:mm:ss 'GMT'zzz", CultureInfo.InvariantCulture)),
        ("$randomDatePast", "A random past datetime", () => DateTime.Now.AddDays(-Rng.Next(1, 365)).ToString("ddd MMM dd yyyy HH:mm:ss 'GMT'zzz", CultureInfo.InvariantCulture)),
        ("$randomDateRecent", "A random recent datetime", () => DateTime.Now.AddMinutes(-Rng.Next(1, 10080)).ToString("ddd MMM dd yyyy HH:mm:ss 'GMT'zzz", CultureInfo.InvariantCulture)),
        ("$randomWeekday", "A random weekday", () => Pick(new[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" })),
        ("$randomMonth", "A random month", () => Pick(new[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" })),

        // Domains, emails, and usernames
        ("$randomDomainName", "A random domain name", () => $"{Pick(FirstNames).ToLowerInvariant()}.{Pick(new[] { "biz", "info", "name", "com", "net" })}"),
        ("$randomDomainSuffix", "A random domain suffix", () => Pick(new[] { "com", "net", "org", "biz", "info", "name", "io" })),
        ("$randomDomainWord", "A random unqualified domain name", () => Pick(FirstNames).ToLowerInvariant()),
        ("$randomEmail", "A random email address", () => $"{Pick(FirstNames)}{Rng.Next(100)}@{Pick(new[] { "gmail.com", "hotmail.com", "yahoo.com" })}"),
        ("$randomExampleEmail", "A random email address from an example domain", () => $"{Pick(FirstNames)}{Rng.Next(100)}@{Pick(new[] { "example.com", "example.net", "example.org" })}"),
        ("$randomUserName", "A random username", () => $"{Pick(FirstNames)}{Pick(new[] { ".", "_", "" })}{Pick(LastNames)}{Rng.Next(100)}"),
        ("$randomUrl", "A random URL", () => $"{Pick(new[] { "https://", "http://" })}{Pick(FirstNames).ToLowerInvariant()}.{Pick(new[] { "net", "com", "name", "info" })}"),

        // Files and directories
        ("$randomFileName", "A random file name", () => $"{Pick(LoremWords)}_{Pick(LoremWords)}.{Pick(new[] { "gdoc", "gif", "mp4v", "key", "sql", "txt" })}"),
        ("$randomFileType", "A random file type", () => Pick(new[] { "application", "audio", "image", "message", "model", "multipart", "text", "video" })),
        ("$randomFileExt", "A random file extension", () => Pick(new[] { "war", "book", "fsc", "gif", "key", "html", "mp3", "war", "wav" })),
        ("$randomCommonFileName", "A random common file name", () => $"{Pick(LoremWords)}.{Pick(new[] { "mp4", "wav", "png", "jpg", "csv", "doc" })}"),
        ("$randomCommonFileType", "A random common file type", () => Pick(new[] { "application", "audio", "image", "text", "video" })),
        ("$randomCommonFileExt", "A random common file extension", () => Pick(new[] { "m2v", "wav", "png", "jpeg", "pdf", "doc", "csv" })),
        ("$randomFilePath", "A random file path", () => $"/home/{Pick(LoremWords)}_{Pick(LoremWords)}.{Pick(new[] { "cpio", "txt", "png", "log" })}"),
        ("$randomDirectoryPath", "A random directory path", () => Pick(new[] { "/usr/bin", "/root", "/usr/local/bin", "/opt", "/var/log", "/home", "/etc" })),
        ("$randomMimeType", "A random MIME type", () => Pick(new[] { "application/json", "text/plain", "image/png", "audio/mpeg", "video/mp4", "application/xml" })),

        // Stores
        ("$randomPrice", "A random price between 0.00 and 1000.00", () => (Rng.NextDouble() * 1000).ToString("F2", CultureInfo.InvariantCulture)),
        ("$randomProduct", "A random product", () => Pick(new[] { "Towels", "Pizza", "Pants", "Cheese", "Chair", "Computer", "Shoes", "Gloves" })),
        ("$randomProductAdjective", "A random product adjective", () => Pick(new[] { "Unbranded", "Incredible", "Tasty", "Handcrafted", "Refined", "Generic", "Rustic", "Ergonomic" })),
        ("$randomProductMaterial", "A random product material", () => Pick(new[] { "Steel", "Plastic", "Frozen", "Concrete", "Cotton", "Granite", "Rubber", "Wooden" })),
        ("$randomProductName", "A random product name", () => $"{Pick(new[] { "Handmade", "Refined", "Ergonomic", "Rustic" })} {Pick(new[] { "Concrete", "Steel", "Rubber", "Cotton" })} {Pick(new[] { "Tuna", "Hat", "Chair", "Shoes" })}"),
        ("$randomDepartment", "A random commerce category", () => Pick(new[] { "Tools", "Movies", "Electronics", "Books", "Garden", "Toys", "Health", "Music" })),

        // Grammar
        ("$randomNoun", "A random noun", () => Pick(Nouns)),
        ("$randomVerb", "A random verb", () => Pick(Verbs)),
        ("$randomIngverb", "A random verb ending in -ing", () => Pick(IngVerbs)),
        ("$randomAdjective", "A random adjective", () => Pick(Adjectives)),
        ("$randomWord", "A random word", () => Pick(WordPool)),
        ("$randomWords", "Some random words", () => RandomWords(Rng.Next(2, 6))),
        ("$randomPhrase", "A random phrase", () => $"{Pick(new[] { "You can't", "Try to", "We need to", "I'll" })} {Pick(Verbs)} the {Pick(Nouns)}!"),

        // Lorem ipsum
        ("$randomLoremWord", "A random word of lorem ipsum text", () => Pick(LoremWords)),
        ("$randomLoremWords", "Some random words of lorem ipsum text", () => LoremWordsN(Rng.Next(2, 5))),
        ("$randomLoremSentence", "A random sentence of lorem ipsum text", () => LoremSentence()),
        ("$randomLoremSentences", "A random 2 to 6 sentences of lorem ipsum text", () => string.Join(" ", Enumerable.Range(0, Rng.Next(2, 7)).Select(_ => LoremSentence()))),
        ("$randomLoremParagraph", "A random paragraph of lorem ipsum text", () => LoremParagraph()),
        ("$randomLoremParagraphs", "3 random paragraphs of lorem ipsum text", () => string.Join("\n", Enumerable.Range(0, 3).Select(_ => LoremParagraph()))),
        ("$randomLoremText", "A random amount of lorem ipsum text", () => string.Join(" ", Enumerable.Range(0, Rng.Next(3, 8)).Select(_ => LoremSentence()))),
        ("$randomLoremSlug", "A random lorem ipsum URL slug", () => string.Join("-", Enumerable.Range(0, 3).Select(_ => Pick(LoremWords)))),
        ("$randomLoremLines", "1 to 5 random lines of lorem ipsum", () => string.Join("\n", Enumerable.Range(0, Rng.Next(1, 6)).Select(_ => LoremSentence()))),
    };

    // ---- Helpers -------------------------------------------------------------

    private static string Pick(string[] pool) => pool[Rng.Next(pool.Length)];

    private static string RandomString(string alphabet, int length) =>
        new(Enumerable.Range(0, length).Select(_ => alphabet[Rng.Next(alphabet.Length)]).ToArray());

    private static string RandomIPv6() =>
        string.Join(":", Enumerable.Range(0, 8).Select(_ => Rng.Next(0x10000).ToString("x4", CultureInfo.InvariantCulture)));

    private static string RandomWords(int count) =>
        Capitalize(string.Join(" ", Enumerable.Range(0, count).Select(_ => Pick(WordPool))));

    private static string LoremWordsN(int count) =>
        string.Join(" ", Enumerable.Range(0, count).Select(_ => Pick(LoremWords)));

    private static string LoremSentence()
    {
        var count = Rng.Next(4, 10);
        return Capitalize(LoremWordsN(count)) + ".";
    }

    private static string LoremParagraph() =>
        string.Join(" ", Enumerable.Range(0, Rng.Next(3, 7)).Select(_ => LoremSentence()));

    private static string Capitalize(string text) =>
        string.IsNullOrEmpty(text) ? text : char.ToUpperInvariant(text[0]) + text[1..];
}
