import clsx from "clsx";
import { Eye, EyeOff, FileText, HardDrive, Lock, Trash2 } from "lucide-react";
import { type ReactNode, useState } from "react";
import { CodeEditor, type VariableSource } from "../editor/CodeEditor";

export interface Row {
  key: string;
  value: string;
  description?: string;
  enabled?: boolean;
  secret?: boolean;
  local?: boolean;
}

interface Props<T extends Row> {
  rows: T[];
  onChange: (rows: T[]) => void;
  /** Builds a fresh row when the user types into the trailing blank row. */
  blank: () => T;
  variables?: VariableSource;
  keyPlaceholder?: string;
  valuePlaceholder?: string;
  showDescription?: boolean;
  /** Rows without an enabled checkbox (path variables). */
  noToggle?: boolean;
  /** Fixed rows shown first and not editable (e.g. the generated User-Agent). */
  locked?: { key: string; value: string; note?: string }[];
  /** Extra cell between key and value (form-data Text/File switch). */
  renderExtra?: (row: T, update: (patch: Partial<T>) => void) => ReactNode;
  /** Replaces the value cell for some rows (file picker). */
  renderValue?: (row: T, update: (patch: Partial<T>) => void) => ReactNode | undefined;
  secrets?: boolean;
  /** Per-row switch between saving the value in the file and keeping it on this machine. */
  localValues?: boolean;
  /** Keys come from the URL (path variables) and can't be edited or added. */
  fixedKeys?: boolean;
  bulk?: boolean;
}

/** Spreadsheet-style editor with a trailing blank row and optional bulk-edit mode. */
export function KeyValueTable<T extends Row>(props: Props<T>) {
  const [bulk, setBulk] = useState(false);
  const { rows, onChange, blank, variables, showDescription, noToggle, locked, renderExtra, renderValue, secrets, localValues, fixedKeys } = props;
  const [revealed, setRevealed] = useState<Set<number>>(new Set());

  const all = fixedKeys ? rows : [...rows, blank()];
  const update = (i: number, patch: Partial<T>) => {
    if (i >= rows.length) {
      onChange([...rows, { ...blank(), ...patch }]);
    } else {
      onChange(rows.map((r, j) => (j === i ? { ...r, ...patch } : r)));
    }
  };
  const remove = (i: number) => onChange(rows.filter((_, j) => j !== i));

  if (bulk) {
    return (
      <div>
        <BulkEditor rows={rows} blank={blank} onChange={onChange} noToggle={noToggle} />
        <div className="mt-2 flex justify-end">
          <button type="button" className="text-12 font-medium text-primary hover:underline" onClick={() => setBulk(false)}>
            Key-value edit
          </button>
        </div>
      </div>
    );
  }

  return (
    <div>
      <table className="kv-table">
        <thead>
          <tr>
            {!noToggle && <th className="w-9" aria-label="Enabled" />}
            <th className="w-[32%]">Key</th>
            {renderExtra && <th className="w-24">Type</th>}
            <th>Value</th>
            {showDescription && <th className="w-[24%]">Description</th>}
            <th className="w-10" aria-label="Actions" />
          </tr>
        </thead>
        <tbody>
          {locked?.map((l) => (
            <tr key={`locked-${l.key}`} className="bg-subtle" title={l.note}>
              {!noToggle && (
                <td className="text-center">
                  <input type="checkbox" className="check opacity-50" checked readOnly disabled aria-label={`${l.key} always sent`} />
                </td>
              )}
              <td className="px-2.5 text-13 text-muted">{l.key}</td>
              {renderExtra && <td />}
              <td className="px-2.5 font-mono text-12 text-muted">{l.value}</td>
              {showDescription && <td className="px-2.5 text-12 text-muted">{l.note}</td>}
              <td className="text-center text-muted">
                <Lock size={13} className="inline" aria-label="Generated by Yamlet" />
              </td>
            </tr>
          ))}
          {all.map((row, i) => {
            const isBlank = i >= rows.length;
            const enabled = row.enabled !== false;
            const masked = secrets && row.secret && !revealed.has(i);
            const custom = renderValue?.(row, (p) => update(i, p));
            return (
              <tr key={i} className={clsx(!enabled && !isBlank && "opacity-55")}>
                {!noToggle && (
                  <td className="text-center">
                    {!isBlank && (
                      <input
                        type="checkbox"
                        className="check"
                        checked={enabled}
                        aria-label={`Enable ${row.key || "row"}`}
                        onChange={(e) => update(i, { enabled: e.target.checked } as Partial<T>)}
                      />
                    )}
                  </td>
                )}
                <td>
                  <input
                    className="kv-cell font-mono text-12"
                    value={row.key}
                    readOnly={fixedKeys}
                    placeholder={props.keyPlaceholder ?? "Key"}
                    aria-label="Key"
                    onChange={(e) => update(i, { key: e.target.value } as Partial<T>)}
                  />
                </td>
                {renderExtra && <td className="px-1.5">{!isBlank && renderExtra(row, (p) => update(i, p))}</td>}
                <td className="relative">
                  {custom ??
                    (masked ? (
                      <input
                        className="kv-cell font-mono text-12"
                        type="password"
                        value={row.value}
                        aria-label="Value"
                        onChange={(e) => update(i, { value: e.target.value } as Partial<T>)}
                      />
                    ) : (
                      <div className="px-2.5">
                        <CodeEditor
                          singleLine
                          value={row.value}
                          variables={variables}
                          placeholder={props.valuePlaceholder ?? "Value"}
                          ariaLabel="Value"
                          onChange={(v) => {
                            if (v !== row.value) update(i, { value: v } as Partial<T>);
                          }}
                        />
                      </div>
                    ))}
                </td>
                {showDescription && (
                  <td>
                    <input
                      className="kv-cell text-12"
                      value={row.description ?? ""}
                      placeholder="Description"
                      aria-label="Description"
                      onChange={(e) => update(i, { description: e.target.value } as Partial<T>)}
                    />
                  </td>
                )}
                <td className="text-center whitespace-nowrap">
                  {!isBlank && (
                    <span className="inline-flex items-center">
                      {localValues && (
                        <button
                          type="button"
                          title={row.local ? "Value kept on this machine only: click to save it in the file" : "Value saved in the file: click to keep it on this machine only"}
                          aria-label={row.local ? `Save ${row.key || "value"} in the file` : `Keep ${row.key || "value"} local`}
                          aria-pressed={!!row.local}
                          className={clsx("rounded p-1", row.local ? "text-primary" : "text-faint hover:text-grey")}
                          onClick={() => update(i, { local: row.local ? undefined : true } as Partial<T>)}
                        >
                          {row.local ? <HardDrive size={13} aria-hidden /> : <FileText size={13} aria-hidden />}
                        </button>
                      )}
                      {secrets && (
                        <button
                          type="button"
                          title={row.secret ? "Secret: click to make plain" : "Mark as secret"}
                          aria-label={row.secret ? "Make plain" : "Mark as secret"}
                          className={clsx("rounded p-1", row.secret ? "text-primary" : "text-faint hover:text-grey")}
                          onClick={() => {
                            if (row.secret && !revealed.has(i)) {
                              setRevealed(new Set(revealed).add(i));
                              return;
                            }
                            const next = new Set(revealed);
                            next.delete(i);
                            setRevealed(next);
                            update(i, { secret: !row.secret } as Partial<T>);
                          }}
                        >
                          {row.secret && !revealed.has(i) ? <EyeOff size={13} aria-hidden /> : <Eye size={13} aria-hidden />}
                        </button>
                      )}
                      {!fixedKeys && (
                        <button type="button" aria-label={`Delete ${row.key || "row"}`} className="rounded p-1 text-faint hover:text-danger" onClick={() => remove(i)}>
                          <Trash2 size={13} aria-hidden />
                        </button>
                      )}
                    </span>
                  )}
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
      {props.bulk !== false && !fixedKeys && (
        <div className="mt-2 flex justify-end">
          <button type="button" className="text-12 font-medium text-primary hover:underline" onClick={() => setBulk(true)}>
            Bulk edit
          </button>
        </div>
      )}
    </div>
  );
}

function BulkEditor<T extends Row>({ rows, blank, onChange, noToggle }: { rows: T[]; blank: () => T; onChange: (rows: T[]) => void; noToggle?: boolean }) {
  const [text, setText] = useState(() => rows.map((r) => `${r.enabled === false && !noToggle ? "// " : ""}${r.key}: ${r.value}`).join("\n"));
  const apply = (t: string) => {
    setText(t);
    const next: T[] = [];
    for (const line of t.split("\n")) {
      if (!line.trim()) continue;
      const disabled = /^\s*\/\//.test(line);
      const body = line.replace(/^\s*\/\/\s?/, "");
      const idx = body.indexOf(":");
      const key = (idx >= 0 ? body.slice(0, idx) : body).trim();
      const value = idx >= 0 ? body.slice(idx + 1).trim() : "";
      const prev = rows.find((r) => r.key === key);
      next.push({ ...blank(), ...prev, key, value, enabled: !disabled });
    }
    onChange(next);
  };
  return (
    <div>
      <textarea
        className="input h-48 resize-y py-2 font-mono text-12 leading-5"
        value={text}
        spellCheck={false}
        aria-label="Bulk edit"
        onChange={(e) => apply(e.target.value)}
      />
      <p className="mt-1 text-11 text-muted">One `key: value` per line. Prefix a line with // to disable it.</p>
    </div>
  );
}
